### ISSUE TITLE
Training code is not giving any output

### ISSUE THREAD

**Issue by farazBhatti** [Akhilesh64/Image-Segmentation-U-2-Net#4]
I am trying to train using DUT dataset. after I ran code U2-net.py nothing gets output. I am expecting output of learning, loss and current number of iterations. Any idea? thanks

**Comment by Akhilesh64** [comment]
I have trained the models using the given scripts only. I need more info on the problem you are facing.

**Comment by farazBhatti** [comment]
During loading of images data loader does not output anything, I am using a dataset of 15000 images to train this model. during loading of the image it looked as if nothing is happening but in fact, images were being read and loaded.
