### ISSUE TITLE
Data loader takes too long to load data

### ISSUE THREAD

**Issue by farazBhatti** [Akhilesh64/Image-Segmentation-U-2-Net#5]
Hi, I have a dataset of about 30,000 images for training. It take for ever to load them. Is there other way which is faster to load this amount of data? thanks

**Comment by Akhilesh64** [comment]
Sorry for the late reply. You can write custom data generators for your purpose. Some references can be found below:
1. [https://github.com/Akhilesh64/ResUnet-a](https://github.com/Akhilesh64/ResUnet-a)
2. [https://towardsdatascience.com/implementing-custom-data-generators-in-keras-de56f013581c](https://towardsdatascience.com/implementing-custom-data-generators-in-keras-de56f013581c)
3. [https://github.com/lim-anggun/Keras-ImageDataGenerator](https://github.com/lim-anggun/Keras-ImageDataGenerator)

Hope this helps.
