### ISSUE TITLE
error from the predict file

### ISSUE THREAD

**Issue by KevorkSulahian** [Akhilesh64/Image-Segmentation-U-2-Net#6]
I trained for 100 epochs as a test on the train data from DUTS using the duts train script but I got an error after running the predict file

ValueError: Mismatch between expected batch size and model output batch size. Output shape = (7, 1, 256, 256, 1), expected output shape = shape (1, 1, 256, 256, 1) 

using tf 2.1

**Comment by Akhilesh64** [comment]
I trained and tested using TensorFlow version 2.4.1,  keras version 2.4.3. Try them and respond if the prediction works. I think this issue is due to the earlier version of tensorflow.

**Comment by KevorkSulahian** [comment]
upgrading fixed my problem, make sure to include the version in the MD so someone else won't have the same problems, and I have another question if it's not to much, in testing we are outputting 7 images, the first one is supposed to be the main output right?

**Comment by Akhilesh64** [comment]
Yeah i will update the Readme file regarding this. About the output images, the first one is the main output obtained by stacking all the other images obtained. Refer to this [link](https://github.com/xuebinqin/U-2-Net/blob/master/figures/U2NETPR.png) for more clarity.
