### ISSUE TITLE
predict.py   TypeError: __init__() got an unexpected keyword argument 'ragged'

### ISSUE THREAD

**Issue by homxxx** [Akhilesh64/Image-Segmentation-U-2-Net#7]

**Comment by Akhilesh64** [comment]
I need more details to reproduce this issue.

**Comment by Akhilesh64** [comment]
Make sure you are runnng the scripts with the tf and keras versions mentioned in the repo. An alternate solution can be found here : [https://stackoverflow.com/questions/58878421/unexpected-keyword-argument-ragged-in-keras](https://stackoverflow.com/questions/58878421/unexpected-keyword-argument-ragged-in-keras).
